# Generated by Django 3.1.7 on 2021-03-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailysales', models.IntegerField()),
                ('dailyper', models.IntegerField()),
                ('monthlysales', models.IntegerField()),
                ('monthlyper', models.IntegerField()),
                ('anualsales', models.IntegerField()),
                ('anualper', models.IntegerField()),
            ],
        ),
    ]
